name: Atmosphere_Kit

on:
  push:
    branches:
      - main
    paths:
      - "README.md"
      - "atmosphere_kit.sh"
  workflow_dispatch:

permissions:
  contents: write

env:
  SCRIPT_SH: atmosphere_kit.sh
  TZ: Asia/Shanghai
  MY_90DNS_IP: 95.216.149.205

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: main

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get install -y jq

      - name: "Build & Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
          echo "tag_name=$(date +%Y%m%d)" >> $GITHUB_ENV
          chmod +x $SCRIPT_SH
          ./$SCRIPT_SH
          zip -rq SwitchSD.zip SwitchSD

      - name: Read description.txt
        id: description
        uses: juliangruber/read-file-action@v1
        with:
          path: ./description.txt

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.DATE }}
          allowUpdates: true
          tag: ${{ env.tag_name }}
          commit: main
          body: "${{ steps.description.outputs.content }}"
          artifacts: "SwitchSD.zip"

      - name: Delete releases and workflows runs
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          releases_keep_latest: 1
          delete_workflows: true
          workflows_keep_day: 0
          gh_token: ${{ secrets.GITHUB_TOKEN }}
